import Link from "next/link";
import { getDocs } from "@/lib/utils";

export default function Home() {
  const docs = getDocs();

  return (
    <main>
      <h1>Home Page</h1>
      <p>
        Click the link below to navigate to a page generated by{" "}
        <code>next-mdx-remote</code>.
      </p>
      <ul>
        {docs.map((doc) => (
          <li key={doc.slug}>
            <Link href={`/docs/${doc.slug}`}>{doc.metadata.title}</Link>
          </li>
        ))}
      </ul>
    </main>
  );
}
